// <auto-generated />
using System;
using InvestManage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestManage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvestManageDbContext))]
    partial class InvestManageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestManage.Domain.Accounts.AccountInvestment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestmentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestmentItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentItemId");

                    b.HasIndex("InvestmentAccountId", "InvestmentItemId")
                        .IsUnique();

                    b.ToTable("AccountInvestments", (string)null);
                });

            modelBuilder.Entity("InvestManage.Domain.Accounts.InvestmentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("InvestmentAccounts", (string)null);
                });

            modelBuilder.Entity("InvestManage.Domain.Currencies.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("InvestManage.Domain.Investments.InvestmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("NormalizedCode");

                    b.ToTable("InvestmentItems", (string)null);
                });

            modelBuilder.Entity("InvestManage.Domain.Prices.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestmentItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentItemId", "PriceDate", "Type", "Source")
                        .IsUnique();

                    b.ToTable("PriceHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_PriceHistory_Price_Positive", "[Price] > 0");
                        });
                });

            modelBuilder.Entity("InvestManage.Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountInvestmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<decimal>("Fees")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<DateOnly?>("SettlementDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("AccountInvestmentId", "TradeDate");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Fees_NotNegative", "[Fees] >= 0");

                            t.HasCheckConstraint("CK_Transactions_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_Transactions_SettlementDate", "[SettlementDate] IS NULL OR [SettlementDate] >= [TradeDate]");

                            t.HasCheckConstraint("CK_Transactions_UnitPrice_Positive", "[UnitPrice] > 0");
                        });
                });

            modelBuilder.Entity("InvestManage.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("InvestManage.Domain.Accounts.AccountInvestment", b =>
                {
                    b.HasOne("InvestManage.Domain.Accounts.InvestmentAccount", null)
                        .WithMany()
                        .HasForeignKey("InvestmentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestManage.Domain.Investments.InvestmentItem", null)
                        .WithMany()
                        .HasForeignKey("InvestmentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestManage.Domain.Accounts.InvestmentAccount", b =>
                {
                    b.HasOne("InvestManage.Domain.Currencies.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestManage.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestManage.Domain.Investments.InvestmentItem", b =>
                {
                    b.HasOne("InvestManage.Domain.Currencies.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestManage.Domain.Prices.PriceHistory", b =>
                {
                    b.HasOne("InvestManage.Domain.Investments.InvestmentItem", null)
                        .WithMany()
                        .HasForeignKey("InvestmentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestManage.Domain.Transactions.Transaction", b =>
                {
                    b.HasOne("InvestManage.Domain.Accounts.AccountInvestment", null)
                        .WithMany()
                        .HasForeignKey("AccountInvestmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestManage.Domain.Currencies.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
