<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>InvestManage.Wpf</AssemblyName>
    <RootNamespace>InvestManage.Wpf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InvestManage.Client\InvestManage.Client.csproj" />
    <ProjectReference Include="..\InvestManage.Contracts\InvestManage.Contracts.csproj" />
  </ItemGroup>
</Project>
